### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by 1024jp** [brutella/TextViewLineNumbers#1]
Hi, I'm one of the developers of the CotEditor project.
Thank you for extracting and translating our line number view code into Swift.
It's really interesting to me and may help other Cocoa developers.

Well, reading your code, I noticed that this project is licensed under the MIT license.
I generally also like the MIT license. 
However, since CotEditor's source code is distributed under the GNU General Public License,
you need to publish your version also under GPL.

Thanks for your understanding in advance.

**Comment by brutella** [comment]
Uh, I missed that. Thanks for pointing this out.

**Comment by 1024jp** [comment]
I appreciate your quick fix :)))
