### ISSUE TITLE
Add Syntax Support?

### ISSUE THREAD

**Issue by hamin** [brutella/TextViewLineNumbers#2]
Love what you've done here. Would love to have a syntax highlighter textview that actually works. This seems like a great start. Would be great to add syntax highlighting support. Perhaps port over the work done in CotEditor?

Would love to help out if i can :)

**Comment by brutella** [comment]
Syntax highlighting is a broad field and not easy. I would be happy if you use my work as a starting point for a more sophisticated text editor. But I have no intentions to add this to the project.
